config/routes.rb
Rails.application.routes.draw do
  resource :session
  resource :registration, only: [ :new, :create ]
  resources :passwords, param: :token

  get "up" => "rails/health#show", as: :rails_health_check

  resources :races, only: [ :index, :new, :create, :show, :update ] do
    member do
      post :start
    end
  end

  resources :participations, only: [ :index, :create, :update ]
  root "races#index"
end

app/views/shared/_navbar.html.erb
<nav id="nav" class="bg-gray-800 p-5 w-screen max-w-full">
  <div class="container mx-auto flex flex-wrap justify-between items-center ">
    <%= link_to 'HotRacer', root_path, class: 'text-white font-bold hover:text-purple-700' %>
    <div class="hidden sm:flex flex-col sm:flex-row items-center space-x-4 w-full sm:w-auto" id="menu">
      <div class="flex flex-col sm:flex-row sm:space-x-4">
        <% if authenticated? %>
          <span class="block mt-2">
            <%= link_to "History", participations_path, class: "hover:text-purple-700 text-white font-bold py-2 px-4 hover:cursor-pointer" %>
          </span>
          <span class="block">
            <%= button_to "Logout", session_path, method: :delete, class: "hover:text-purple-700 text-white font-bold py-2 px-4 hover:cursor-pointer" %>
          </span>
        <% else %>
          <span class="block">
            <%= link_to "Sign up", new_registration_path, class: "hover:text-purple-700 text-white font-bold py-2 px-4 hover:cursor-pointer" %>
          </span>
          <span class="block">
            <%= link_to "Login", new_session_path, class: "hover:text-purple-700 text-white font-bold py-2 px-4 hover:cursor-pointer" %>
          </span>
        <% end %>
      </div>
    </div>
  </div>
</nav>